name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: |
          dotnet publish -c Release

      - name: Zip artifact
        run: |
          Compress-Archive -Path out/* -DestinationPath OwChatAssistant.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: OwChatAssistant.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
